[package]
name = "misty-document-processing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hex = "0.4"
zune-psd = "0.5.1"
calamine = "0.31"
csv = "1"
pdf-extract = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
zip = { version = "4.6.1", default-features = false, features = ["deflate"] }

image = { version = "0.25.10", default-features = false, features = ["bmp", "gif", "hdr", "jpeg", "png", "pnm", "tga", "webp"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
strip = "symbols"

[profile.release.build-override]
strip = false
