/** Extension and MIME lookup tables shared by every preview surface. */

export const textExtensions = new Set([
  "txt",
  "text",
  "log",
  "md",
  "markdown",
  "toml",
  "yaml",
  "yml",
  "ini",
  "conf",
  "cfg",
  "csv",
  "tsv",
  "rs",
  "go",
  "js",
  "jsx",
  "ts",
  "tsx",
  "css",
  "html",
  "xml",
  "sh",
  "zsh",
  "bash",
  "fish",
  "py",
  "rb",
  "java",
  "c",
  "h",
  "cpp",
  "hpp",
  "swift",
  "kt",
  "sql",
  "json",
  "jsonc",
]);

export const officeExtensions = new Set([
  "docx",
  "xlsx",
  "pptx",
  "odt",
  "ods",
  "odp",
  "epub",
  "rtf",
  "doc",
  "xls",
  "ppt",
]);

export const archiveExtensions = new Set([
  "zip",
  "tar",
  "tgz",
  "gz",
  "tbz",
  "tbz2",
  "bz2",
  "txz",
  "xz",
  "7z",
  "rar",
]);

export const imageMimeTypes: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  bmp: "image/bmp",
  webp: "image/webp",
  avif: "image/avif",
  ico: "image/x-icon",
  svg: "image/svg+xml",
  heic: "image/heic",
  heif: "image/heif",
  tga: "image/x-tga",
  psd: "image/vnd.adobe.photoshop",
  pnm: "image/x-portable-anymap",
  ppm: "image/x-portable-pixmap",
  pgm: "image/x-portable-graymap",
};

export const videoMimeTypes: Record<string, string> = {
  mp4: "video/mp4",
  m4v: "video/mp4",
  mov: "video/quicktime",
  webm: "video/webm",
  ogv: "video/ogg",
  mkv: "video/x-matroska",
  avi: "video/x-msvideo",
  mpg: "video/mpeg",
  mpeg: "video/mpeg",
};

export const audioMimeTypes: Record<string, string> = {
  mp3: "audio/mpeg",
  m4a: "audio/mp4",
  aac: "audio/aac",
  wav: "audio/wav",
  flac: "audio/flac",
  ogg: "audio/ogg",
  oga: "audio/ogg",
  opus: "audio/ogg",
  weba: "audio/webm",
  aif: "audio/aiff",
  aiff: "audio/aiff",
  wma: "audio/x-ms-wma",
};
