[package]
name = "misty-file-search"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tantivy = "0.25"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
tempfile = "3"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
strip = "symbols"
